import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Ayan pal",
};

export default function DashboardLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
      <ProtectedRoute>
      <Navbar />
        {children}
      <Footer/>
      </ProtectedRoute>
    </div>
  );
}
